services:
  kafka-broker:
    image: apache/kafka:4.1.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,IN_DOCKER:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,IN_DOCKER://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,IN_DOCKER://kafka-broker:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - yandex6

  kafka-init:
    image: confluentinc/cp-kafka:7.2.15
    depends_on:
      - kafka-broker
    volumes: 
      - ./create-topics.sh:/create-topics.sh
    entrypoint: [ "sh", "/create-topics.sh" ]
    networks:
      - yandex6

  schema-registry:
    image: confluentinc/cp-schema-registry:8.1.0
    depends_on:
      - kafka-broker
    ports:
      - "8081:8080"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker:9094
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8080
    networks:
      - yandex6

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    depends_on:
      - kafka-broker
      - schema-registry
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9094
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8080
    networks:
      - yandex6

  app:
    depends_on:
      - kafka-broker
      - schema-registry
      - kafka-init
    build:
      context: ./app
    networks:
    - yandex6

  nifi:
    image: apache/nifi:1.21.0
    container_name: nifi
    user: "root"
    ports:
      - "8082:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
    networks:
      - yandex6

volumes:
  nifi_data:

networks:
  yandex6:
